- name: ACS Installation
  hosts: localhost
  vars:
    delete_demo: false
    verify_tls: false
  tasks:
    - name: Check Required Parameters
      ansible.builtin.fail:
        msg: "This play requires 'server' and 'token' to be defined"
      when:
        - (server is not defined) or (token is not defined) or (server is none) or (token is none)
      ignore_errors: false

    - name: Set domain
      ansible.builtin.set_fact:
        domain: "{{ server | regex_replace('https://api.') | regex_replace(':6443') }}"

    - name: Include ACS
      ansible.builtin.include_role:
        name: acs
